all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    infra:
      hosts:
        gitea:
          ansible_host: 10.10.1.125
        monitoring:
          ansible_host: 10.10.1.137

    monitoring_servers:
      hosts:
        monitoring:

    gitea_servers:
      hosts:
        gitea:
