---
sanoid_datasets:
  - dataset: rpool/data
    template: vms
    recursive: true
  - dataset: rpool/ROOT
    template: system
    recursive: true

sanoid_templates:
  vms:
    daily: 7
    weekly: 4
    monthly: 0
    hourly: 0
    frequently: 0
    autosnap: true
    autoprune: true
  system:
    daily: 3
    weekly: 2
    monthly: 0
    hourly: 0
    frequently: 0
    autosnap: true
    autoprune: true

syncoid_jobs:
  - src: rpool/data
    dst: hdd/backups/rpool-data
    recursive: true
  - src: rpool/ROOT/pve-1
    dst: hdd/backups/pve-root
    recursive: false

syncoid_schedule: "*-*-* 02:00:00"
syncoid_randomized_delay: 10min
