---
- name: Common setup for all Arch VMs
  hosts: all:!pihole_servers:!traefik_servers
  roles:
    - common
    - node_exporter
    - promtail

- name: Monitoring stack
  hosts: monitoring_servers
  roles:
    - monitoring

- name: Gitea
  hosts: gitea_servers
  roles:
    - gitea

- name: Pi-hole
  hosts: pihole_servers
  roles:
    - pihole

- name: Traefik
  hosts: traefik_servers
  roles:
    - traefik
