---
traefik_version: "3.3.4"
traefik_http_port: 80
traefik_https_port: 443
traefik_dashboard_port: 8080
traefik_log_level: "INFO"
traefik_acme_email: "fanfohcd@gmail.com"

traefik_services:
  - name: gitea
    host: "gitea.homelab"
    backend: "http://10.10.1.125:3000"
    public_host: "adyrem.duckdns.org"
    public_path: "/git"
    strip_prefix: "/git"
  - name: mtg
    host: "mtg.homelab"
    backend: "http://10.10.2.10:3000"
    public_host: "adyrem.duckdns.org"
    public_path: "/mtg"
    strip_prefix: "/mtg"
  - name: grafana
    host: "grafana.homelab"
    backend: "http://10.10.1.137:3000"
  - name: pihole
    host: "pihole.homelab"
    backend: "http://10.10.1.2:80"
  - name: jellyfin
    host: "jellyfin.homelab"
    backend: "http://10.10.1.50:8096"
  - name: jellyseerr
    host: "jellyseerr.homelab"
    backend: "http://10.10.1.50:5055"
  - name: radarr
    host: "radarr.homelab"
    backend: "http://10.10.1.50:7878"
  - name: sonarr
    host: "sonarr.homelab"
    backend: "http://10.10.1.50:8989"
  - name: prowlarr
    host: "prowlarr.homelab"
    backend: "http://10.10.1.50:9696"
  - name: qbittorrent
    host: "qbittorrent.homelab"
    backend: "http://10.10.1.50:5080"
  - name: proxmox
    host: "proxmox.homelab"
    backend: "https://192.168.1.10:8006"
    tls_skip_verify: true
